name:                gtk-gui
version:             0.1.0.0
github:              "RenatAmirov/gtk-gui"
license:             BSD-3-Clause
author:              "RenatAmirov"
maintainer:          "amirov.renat.1st@gmail.com"
copyright:           "rinux"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RenatAmirov/gtk-gui#readme>

dependencies:
- base >= 4.7 && < 5
- text
- gi-pango
- gi-pangocairo
- gtk3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gtk-gui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtk-gui
    - random
    - cairo

tests:
  gtk-gui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtk-gui
